"""updated models to fix analytics

Revision ID: 9f507810a849
Revises: 6cdd6b3cf503
Create Date: 2025-07-28 19:35:06.164615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f507810a849'
down_revision: Union[str, None] = '6cdd6b3cf503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
